### ISSUE TITLE
Définir une zone montagneuse

### ISSUE THREAD

**Issue by LouizaB** [LouizaB/LidarDeveloppement#2]
Pour la zone montagneuse on choisit de rester sur la Restonica pour le moment , il faut extraire le fichier las ou laz ainsi que le fichier raster (tiff).

Cette tache requiert de garder:
le lien du site d'où on a eu les données et le rapport d'extraction

**Comment by LouizaB** [comment]
@Kaoutar-ben  est-ce que c'est ok pour cette tache ? si oui, il faut pusher sur ta branche

**Comment by Kaoutar-ben** [comment]
@LouizaB Non, j'y travaille encore

**Comment by Kaoutar-ben** [comment]
@LouizaB Non, j'y travail encore
