### ISSUE TITLE
Analyse des besoins pour le choix de Base de données Sql/NoSql

### ISSUE THREAD

**Issue by LouizaB** [LouizaB/LidarDeveloppement#9]

**Comment by mastsnaa** [comment]
- On peut utiliser la compression des images pour réduire la taille de la données 
- SQL est limité au stockage donc c'est mieux d'utiliser le nosql

**Comment by LouizaB** [comment]
@mastsnaa , il nous faut une revue et un document d'analyse des besoins pour le choix de la technologie (Il faut penser au rapport final) c'est des éléments de rapport.

**Comment by LouizaB** [comment]
1er prototype de l'interface

**Comment by LouizaB** [comment]
Utilisation de NoSql comme BDD pour le projet
